server.port=8081
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.datasource.url=${SPRING_DB_URL}
spring.datasource.username=${SPRING_DB_USERNAME}
spring.datasource.password=${SPRING_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
scheduler.cron-expression=0 0 18 * * *
scheduler.kafka-topic=EMAIL_SENDING_TASKS
scheduler.max-titles-in-email=5
notifications.title.mixed=Daily Task Summary
notifications.title.finished=Tasks Completed Today
notifications.title.unfinished=Pending Tasks Notification
notifications.finished.header=Tasks completed today:
notifications.unfinished.header=Pending tasks remaining:
notifications.bullet=- 